import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Context from "@/Context/Context";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className=" dark">
      <body className={inter.className}>
        <div className="relative w-full flex items-center bg-black justify-center ">
          <Navbar className=" mt-4 bg-black animate-navGlow border-2 border-white rounded-full" />
        </div>
        {children}
      </body>
    </html>
  );
}
